db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144629422,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "SUAREZ",
    est_primer_nombre: "JHOHAN",
    est_segundo_nombre: "DAVID",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144630346,
    est_primer_apellido: "GUTIERREZ",
    est_segundo_apellido: "OLAVE",
    est_primer_nombre: "JULIAN",
    est_segundo_nombre: "DAVID",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144630718,
    est_primer_apellido: "GUTIERREZ",
    est_segundo_apellido: "QUIROGA",
    est_primer_nombre: "NICOLAS",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144630436,
    est_primer_apellido: "PEREZ",
    est_segundo_apellido: "JIMENEZ",
    est_primer_nombre: "HELEN",
    est_segundo_nombre: "YULIANA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080935259,
    est_primer_apellido: "SABI",
    est_segundo_apellido: "GUTIERREZ",
    est_primer_nombre: "SANTIAGO",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1029965164,
    est_primer_apellido: "STERLING",
    est_segundo_apellido: "QUIROGA",
    est_primer_nombre: "SKARLETT",
    est_segundo_nombre: "XIMENA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1045728016,
    est_primer_apellido: "CHAMBO",
    est_segundo_apellido: "BENAVIDES",
    est_primer_nombre: "ANDRES",
    est_segundo_nombre: "SANTIAGO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628289,
    est_primer_apellido: "PEREZ",
    est_segundo_apellido: "JIMENEZ",
    est_primer_nombre: "JUAN",
    est_segundo_nombre: "CAMILO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628602,
    est_primer_apellido: "STERLING",
    est_segundo_apellido: "CARVAJAL",
    est_primer_nombre: "JHONATAN",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934777,
    est_primer_apellido: "TRIVIÑO",
    est_segundo_apellido: "TORRES",
    est_primer_nombre: "JHIMER",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1145826375,
    est_primer_apellido: "CHAMBO",
    est_segundo_apellido: "BENAVIDES",
    est_primer_nombre: "YEIMI",
    est_segundo_nombre: "TATIANA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1118372223,
    est_primer_apellido: "GALINDEZ",
    est_segundo_apellido: "GOMEZ",
    est_primer_nombre: "ERIKA",
    est_segundo_nombre: "MILETH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1084254228,
    est_primer_apellido: "TORRES",
    est_segundo_apellido: "TRIANA",
    est_primer_nombre: "DANNA",
    est_segundo_nombre: "YULENY",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083901888,
    est_primer_apellido: "TRIVIÑO",
    est_segundo_apellido: "TORRES",
    est_primer_nombre: "INDIRA",
    est_segundo_nombre: "MICHELLE",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144625732,
    est_primer_apellido: "CESPEDES",
    est_segundo_apellido: "GUTIERREZ",
    est_primer_nombre: "DIEGO",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144627120,
    est_primer_apellido: "SABI",
    est_segundo_apellido: "GUTIERREZ",
    est_primer_nombre: "YESENIA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083894944,
    est_primer_apellido: "SUAREZ",
    est_segundo_apellido: "GUZMAN",
    est_primer_nombre: "ANDRES",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1077855983,
    est_primer_apellido: "BARRERA",
    est_segundo_apellido: "RAMIREZ",
    est_primer_nombre: "CARLOS",
    est_segundo_nombre: "ANDRES",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083881201,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "SUAREZ",
    est_primer_nombre: "IVAN",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007905,
    est_nombre_sede: "LA ESPERANZA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083885089,
    est_primer_apellido: "RODRIGUEZ",
    est_segundo_apellido: "ROJAS",
    est_primer_nombre: "GABRIEL",
    est_segundo_nombre: "MATEO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
-- ============================================================================================
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934963,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "CALDERON",
    est_primer_nombre: "MARIA",
    est_segundo_nombre: "LISETH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934478,
    est_primer_apellido: "GARAVITO",
    est_segundo_apellido: "CARVAJAL",
    est_primer_nombre: "CARLOS",
    est_segundo_nombre: "GERARDO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934857,
    est_primer_apellido: "MORALES",
    est_segundo_apellido: "MAMIAN",
    est_primer_nombre: "DANIEL",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934250,
    est_primer_apellido: "ORTIZ",
    est_segundo_apellido: "JOAQUI",
    est_primer_nombre: "MAIKOL",
    est_segundo_nombre: "ALEJANDRO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083907462,
    est_primer_apellido: "SALAMANCA",
    est_segundo_apellido: "ROMERO",
    est_primer_nombre: "LUIS",
    est_segundo_nombre: "SANTIAGO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083903127,
    est_primer_apellido: "STERLING",
    est_segundo_apellido: "TAPIERO",
    est_primer_nombre: "YENIFER",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080933352,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "CALDERON",
    est_primer_nombre: "MARLON",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083894313,
    est_primer_apellido: "GOMEZ",
    est_segundo_apellido: "JOVEN",
    est_primer_nombre: "JESUS",
    est_segundo_nombre: "DAVID",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083898273,
    est_primer_apellido: "MURCIA",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "AILYN",
    est_segundo_nombre: "YULIANA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1019607281,
    est_primer_apellido: "FIGUEROA",
    est_segundo_apellido: "RUGE",
    est_primer_nombre: "JOAN",
    est_segundo_nombre: "SANTIAGO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1084333311,
    est_primer_apellido: "MOTTA",
    est_segundo_apellido: "VARGAS",
    est_primer_nombre: "YURI",
    est_segundo_nombre: "GRACIELA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083893905,
    est_primer_apellido: "OME",
    est_segundo_apellido: "MOTTA",
    est_primer_nombre: "MELITZA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1059359396,
    est_primer_apellido: "ORTIZ",
    est_segundo_apellido: "JOAQUI",
    est_primer_nombre: "JHEILIN",
    est_segundo_nombre: "DEL PILAR",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144625119,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "CALDERON",
    est_primer_nombre: "KAROL",
    est_segundo_nombre: "YULIANI",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144625166,
    est_primer_apellido: "GARZON",
    est_segundo_apellido: "STERLING",
    est_primer_nombre: "JORGE",
    est_segundo_nombre: "EDUARDO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080933028,
    est_primer_apellido: "GUTIERREZ",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "ROQUE",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083891278,
    est_primer_apellido: "MURCIA",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "KEVIN",
    est_segundo_nombre: "ANDRES",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083888778,
    est_primer_apellido: "MUÑOZ",
    est_segundo_apellido: "MEDINA",
    est_primer_nombre: "ARGEMIRO",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083888779,
    est_primer_apellido: "MUÑOZ",
    est_segundo_apellido: "MEDINA",
    est_primer_nombre: "DANIELA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144625452,
    est_primer_apellido: "PINZON",
    est_segundo_apellido: "PEREZ",
    est_primer_nombre: "ALEXANDER",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1083885890,
    est_primer_apellido: "ROMERO",
    est_segundo_apellido: "PRIETO",
    est_primer_nombre: "JUAN",
    est_segundo_nombre: "SEBASTIAN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083882757,
    est_primer_apellido: "ARTUNDUAGA",
    est_segundo_apellido: "MURCIA",
    est_primer_nombre: "EYNER",
    est_segundo_nombre: "SEBASTIAN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083876514,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "CALDERON",
    est_primer_nombre: "BAIRON",
    est_segundo_nombre: "ANDRES",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080933367,
    est_primer_apellido: "GARAVITO",
    est_segundo_apellido: "CARVAJAL",
    est_primer_nombre: "LUCERO",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080933025,
    est_primer_apellido: "GUTIERREZ",
    est_segundo_apellido: "HERRERA",
    est_primer_nombre: "LAURA",
    est_segundo_nombre: "DANIELA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007904,
    est_nombre_sede: "LA FLORIDA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1080931508,
    est_primer_apellido: "GUTIERREZ",
    est_segundo_apellido: "ROMERO",
    est_primer_nombre: "SEBASTIAN",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1081158199,
    est_primer_apellido: "CAMPOS",
    est_segundo_apellido: "MARTINEZ",
    est_primer_nombre: "DINA",
    est_segundo_nombre: "MIRLEY",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080935265,
    est_primer_apellido: "CHATE",
    est_segundo_apellido: "CUELLAR",
    est_primer_nombre: "MAIRA",
    est_segundo_nombre: "ALEXANDRA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144629256,
    est_primer_apellido: "CUCHIMBA",
    est_segundo_apellido: "RAMOS",
    est_primer_nombre: "YEIMI",
    est_segundo_nombre: "TATIANA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083909781,
    est_primer_apellido: "GARCIA",
    est_segundo_apellido: "MARTINEZ",
    est_primer_nombre: "JIMENA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1118374612,
    est_primer_apellido: "GUTIERREZ",
    est_segundo_apellido: "LOPEZ",
    est_primer_nombre: "BRAYAN",
    est_segundo_nombre: "STIVEN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083911023,
    est_primer_apellido: "JAJOY",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "EDWIN",
    est_segundo_nombre: "CAMILO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080935237,
    est_primer_apellido: "MESA",
    est_segundo_apellido: "CASTRO",
    est_primer_nombre: "MARIA",
    est_segundo_nombre: "ALEJANDRA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1076507428,
    est_primer_apellido: "ALBEAR",
    est_segundo_apellido: "ARTUNDUAGA",
    est_primer_nombre: "JEFERSON",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1145727819,
    est_primer_apellido: "CLAROS",
    est_segundo_apellido: "ROJAS",
    est_primer_nombre: "RICARDO",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083902300,
    est_primer_apellido: "GOMEZ",
    est_segundo_apellido: "CERON",
    est_primer_nombre: "CRISTIAN",
    est_segundo_nombre: "CAMILO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934486,
    est_primer_apellido: "HERRERA",
    est_segundo_apellido: "LOPEZ",
    est_primer_nombre: "BREYNER",
    est_segundo_nombre: "STIVEN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628221,
    est_primer_apellido: "ROJAS",
    est_segundo_apellido: "CHATE",
    est_primer_nombre: "ESTEBAN",
    est_segundo_nombre: "ANDRES",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1090934691,
    est_primer_apellido: "ROJAS",
    est_segundo_apellido: "RODRIGUEZ",
    est_primer_nombre: "HAROLD",
    est_segundo_nombre: "STEVEN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1076507427,
    est_primer_apellido: "ALBEAR",
    est_segundo_apellido: "ARTUNDUAGA",
    est_primer_nombre: "SEBASTIAN",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083896609,
    est_primer_apellido: "CAMPOS",
    est_segundo_apellido: "MARTINEZ",
    est_primer_nombre: "WILBER",
    est_segundo_nombre: "ALEXIS",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083899865,
    est_primer_apellido: "CASTRO",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "DANNA",
    est_segundo_nombre: "VALENTINA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1140435075,
    est_primer_apellido: "MUÑOZ",
    est_segundo_apellido: "",
    est_primer_nombre: "YERFERSON",
    est_segundo_nombre: "ANDRES",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1083880523,
    est_primer_apellido: "ALBEAR",
    est_segundo_apellido: "ARTUNDUAGA",
    est_primer_nombre: "KAREN",
    est_segundo_nombre: "YULIETH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083890291,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "CANO",
    est_primer_nombre: "YEISON",
    est_segundo_nombre: "ANDRES",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083885281,
    est_primer_apellido: "CAMPOS",
    est_segundo_apellido: "MARTINEZ",
    est_primer_nombre: "DAVINSON",
    est_segundo_nombre: "ALDAIR",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144626932,
    est_primer_apellido: "HERRERA",
    est_segundo_apellido: "LOPEZ",
    est_primer_nombre: "OSCAR",
    est_segundo_nombre: "ANDRES",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1059765475,
    est_primer_apellido: "CUCHIMBA",
    est_segundo_apellido: "RAMOS",
    est_primer_nombre: "ELKIN",
    est_segundo_nombre: "FARID",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1029883774,
    est_primer_apellido: "ESPAÑA",
    est_segundo_apellido: "AYA",
    est_primer_nombre: "DAIRON",
    est_segundo_nombre: "NICOLAS",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1079536144,
    est_primer_apellido: "FONSECA",
    est_segundo_apellido: "ROJAS",
    est_primer_nombre: "TALIANA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007907,
    est_nombre_sede: "LA PIRAGUA",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1083885792,
    est_primer_apellido: "CORDOBA",
    est_segundo_apellido: "ANACONA",
    est_primer_nombre: "CESAR",
    est_segundo_nombre: "JULIAN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144630315,
    est_primer_apellido: "BARTOLO",
    est_segundo_apellido: "SILVA",
    est_primer_nombre: "SARA",
    est_segundo_nombre: "NICOLE",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080935245,
    est_primer_apellido: "CUBILLOS",
    est_segundo_apellido: "LAGOS",
    est_primer_nombre: "ANGEL",
    est_segundo_nombre: "RICARDO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934965,
    est_primer_apellido: "SAMBONI",
    est_segundo_apellido: "VIQUEZ",
    est_primer_nombre: "EDWAR",
    est_segundo_nombre: "FABIAN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144630332,
    est_primer_apellido: "TEJADA",
    est_segundo_apellido: "GOMEZ",
    est_primer_nombre: "MARIA",
    est_segundo_nombre: "ISABEL",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1082158296,
    est_primer_apellido: "CAMPOS",
    est_segundo_apellido: "CAMERO",
    est_primer_nombre: "DANIELA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628587,
    est_primer_apellido: "CESPEDES",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "ELY",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144629203,
    est_primer_apellido: "CLAROS",
    est_segundo_apellido: "PINILLA",
    est_primer_nombre: "DIEGO",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934694,
    est_primer_apellido: "ESPAÑA",
    est_segundo_apellido: "BRAVO",
    est_primer_nombre: "YESSICA",
    est_segundo_nombre: "ALEXANDRA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083909156,
    est_primer_apellido: "ESPAÑA",
    est_segundo_apellido: "CARVAJAL",
    est_primer_nombre: "MARIANA",
    est_segundo_nombre: "ALEJANDRA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934563,
    est_primer_apellido: "FERNANDEZ",
    est_segundo_apellido: "PARDO",
    est_primer_nombre: "YANDRI",
    est_segundo_nombre: "VANESSA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934437,
    est_primer_apellido: "FUENTES",
    est_segundo_apellido: "CAPADOR",
    est_primer_nombre: "ANDERSON",
    est_segundo_nombre: "SMITH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934639,
    est_primer_apellido: "MACIAS",
    est_segundo_apellido: "CERON",
    est_primer_nombre: "ELIANNY",
    est_segundo_nombre: "ZAMARA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934237,
    est_primer_apellido: "MACIAS",
    est_segundo_apellido: "MORALES",
    est_primer_nombre: "CHELSEA",
    est_segundo_nombre: "MARCELA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628545,
    est_primer_apellido: "MARTINEZ",
    est_segundo_apellido: "ESPAÑA",
    est_primer_nombre: "ISABELLA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083906602,
    est_primer_apellido: "OSA",
    est_segundo_apellido: "ESPAÑA",
    est_primer_nombre: "LAURA",
    est_segundo_nombre: "CAMILA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934720,
    est_primer_apellido: "RODRIGUEZ",
    est_segundo_apellido: "SILVA",
    est_primer_nombre: "JOSE",
    est_segundo_nombre: "MANUEL",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1118372285,
    est_primer_apellido: "DIAZ",
    est_segundo_apellido: "VARGAS",
    est_primer_nombre: "JORGE",
    est_segundo_nombre: "DANIEL",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080933561,
    est_primer_apellido: "SAMBONI",
    est_segundo_apellido: "VIQUEZ",
    est_primer_nombre: "JHESIKA",
    est_segundo_nombre: "ROCIO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144625501,
    est_primer_apellido: "FERNANDEZ",
    est_segundo_apellido: "PEREZ",
    est_primer_nombre: "JOHEL",
    est_segundo_nombre: "MAURICIO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1084333150,
    est_primer_apellido: "GARZON",
    est_segundo_apellido: "MENA",
    est_primer_nombre: "KAROL",
    est_segundo_nombre: "JULIAN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1014216578,
    est_primer_apellido: "MUÑOZ",
    est_segundo_apellido: "MURCIA",
    est_primer_nombre: "LUIS",
    est_segundo_nombre: "DAVID",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1084332823,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "ALVIRA",
    est_primer_nombre: "AURA",
    est_segundo_nombre: "JULIANA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144625229,
    est_primer_apellido: "CESPEDES",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "ANA",
    est_segundo_nombre: "MARIA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1079534556,
    est_primer_apellido: "FUENTES",
    est_segundo_apellido: "CAPADOR",
    est_primer_nombre: "JHOJAN",
    est_segundo_nombre: "ARMANDO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007902,
    est_nombre_sede: "MATEO RICO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1084332898,
    est_primer_apellido: "VELANDIA",
    est_segundo_apellido: "FUENTES",
    est_primer_nombre: "SEBASTIAN",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080935298,
    est_primer_apellido: "CHIMBORAZO",
    est_segundo_apellido: "OLAVE",
    est_primer_nombre: "LAURA",
    est_segundo_nombre: "SOFIA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1084334631,
    est_primer_apellido: "CALVO",
    est_segundo_apellido: "CLAROS",
    est_primer_nombre: "HEILYN",
    est_segundo_nombre: "GABRIELA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934544,
    est_primer_apellido: "GAMBOA",
    est_segundo_apellido: "ANDRADE",
    est_primer_nombre: "KAREN",
    est_segundo_nombre: "YULIETH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083902828,
    est_primer_apellido: "PARRA",
    est_segundo_apellido: "BALANTA",
    est_primer_nombre: "MARIA",
    est_segundo_nombre: "BALANTA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1075272310,
    est_primer_apellido: "RIVERA",
    est_segundo_apellido: "SANCHEZ",
    est_primer_nombre: "ALEJANDRA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1075272312,
    est_primer_apellido: "RIVERA",
    est_segundo_apellido: "SANCHEZ",
    est_primer_nombre: "MADELEYNE",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628985,
    est_primer_apellido: "TORRES",
    est_segundo_apellido: "SERRANO",
    est_primer_nombre: "KEVIN",
    est_segundo_nombre: "ALEJANDRO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1077862890,
    est_primer_apellido: "ALVIZ",
    est_segundo_apellido: "HIGON",
    est_primer_nombre: "JUAN",
    est_segundo_nombre: "CAMILO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1145726436,
    est_primer_apellido: "ALVIZ",
    est_segundo_apellido: "HIGON",
    est_primer_nombre: "JUAN",
    est_segundo_nombre: "CARLOS",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934690,
    est_primer_apellido: "CRUZ",
    est_segundo_apellido: "BELTRAN",
    est_primer_nombre: "KAREN",
    est_segundo_nombre: "DANIELA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628075,
    est_primer_apellido: "PULGAR",
    est_segundo_apellido: "MORENO",
    est_primer_nombre: "XIOMARA",
    est_segundo_nombre: "CAMILA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083892256,
    est_primer_apellido: "CORREA",
    est_segundo_apellido: "BOTINA",
    est_primer_nombre: "ANDRY",
    est_segundo_nombre: "SOFIA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083894277,
    est_primer_apellido: "NUNEZ",
    est_segundo_apellido: "CORREA",
    est_primer_nombre: "NICOLLE",
    est_segundo_nombre: "DANIELA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083890546,
    est_primer_apellido: "RODRIGUEZ",
    est_segundo_apellido: "MORENO",
    est_primer_nombre: "JULIAN",
    est_segundo_nombre: "ANDRES",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1084333343,
    est_primer_apellido: "TRUJILLO",
    est_segundo_apellido: "OSORIO",
    est_primer_nombre: "IVAN",
    est_segundo_nombre: "DANIEL",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080932105,
    est_primer_apellido: "CHIMBORAZO",
    est_segundo_apellido: "OLAVE",
    est_primer_nombre: "JUAN",
    est_segundo_nombre: "SEBASTIAN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1081512414,
    est_primer_apellido: "MUÑOZ",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "MARLI",
    est_segundo_nombre: "YASMIN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083885323,
    est_primer_apellido: "CARDONA",
    est_segundo_apellido: "PARRA",
    est_primer_nombre: "MANUEL",
    est_segundo_nombre: "SANTIAGO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1062754171,
    est_primer_apellido: "CORDOBA",
    est_segundo_apellido: "CUSI",
    est_primer_nombre: "EDID",
    est_segundo_nombre: "YURANI",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1079535942,
    est_primer_apellido: "CORREA",
    est_segundo_apellido: "ROJAS",
    est_primer_nombre: "EDWIN",
    est_segundo_nombre: "JHAN CARLOS",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007906,
    est_nombre_sede: "PAQUIES",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1080930662,
    est_primer_apellido: "ORTEGA",
    est_segundo_apellido: "OLAVE",
    est_primer_nombre: "YOMAR",
    est_segundo_nombre: "ALEXANDER",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083911283,
    est_primer_apellido: "ARTUNDUAGA",
    est_segundo_apellido: "BRAVO",
    est_primer_nombre: "NICOLAS",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083910135,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "CALDERON",
    est_primer_nombre: "MARIA",
    est_segundo_nombre: "ISABEL",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144629154,
    est_primer_apellido: "CUMACO",
    est_segundo_apellido: "VARGAS",
    est_primer_nombre: "CINDY",
    est_segundo_nombre: "ALEXANDRA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628646,
    est_primer_apellido: "DUCUARA",
    est_segundo_apellido: "CEBALLOS",
    est_primer_nombre: "SHIRLEY",
    est_segundo_nombre: "JIMENA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144630216,
    est_primer_apellido: "GOMEZ",
    est_segundo_apellido: "DIAZ",
    est_primer_nombre: "DANA",
    est_segundo_nombre: "NICOL",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1075802328,
    est_primer_apellido: "GUTIERREZ",
    est_segundo_apellido: "SALGADO",
    est_primer_nombre: "JHON",
    est_segundo_nombre: "STIBEN",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1073243152,
    est_primer_apellido: "SILVA",
    est_segundo_apellido: "CUELLAR",
    est_primer_nombre: "JULIAN",
    est_segundo_nombre: "DANIEL",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "GRADO 0",
    est_sector: "OFICIAL",
    est_grupo: 1,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083911079,
    est_primer_apellido: "TRUJILLO",
    est_segundo_apellido: "MOLINA",
    est_primer_nombre: "LEIDY",
    est_segundo_nombre: "CAROLINA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083899528,
    est_primer_apellido: "ALDANA",
    est_segundo_apellido: "MOLINA",
    est_primer_nombre: "DANIEL",
    est_segundo_nombre: "FELIPE",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628606,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "ARTUNDUAGA",
    est_primer_nombre: "VALERIA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080934716,
    est_primer_apellido: "GARZON",
    est_segundo_apellido: "CUELLAR",
    est_primer_nombre: "DARLI",
    est_segundo_nombre: "YULIETH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144628861,
    est_primer_apellido: "MEDINA",
    est_segundo_apellido: "CALDERON",
    est_primer_nombre: "MARIA",
    est_segundo_nombre: "ALEJANDRA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083898531,
    est_primer_apellido: "TRUJILLO",
    est_segundo_apellido: "MOLINA",
    est_primer_nombre: "EDUAR",
    est_segundo_nombre: "SANTIAGO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "PRIMERO",
    est_sector: "OFICIAL",
    est_grupo: 101,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083902595,
    est_primer_apellido: "TRUJILLO",
    est_segundo_apellido: "PERDOMO",
    est_primer_nombre: "YAIR",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144626542,
    est_primer_apellido: "CARVAJAL",
    est_segundo_apellido: "VARGAS",
    est_primer_nombre: "JOSE",
    est_segundo_nombre: "OCTAVIO",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144627655,
    est_primer_apellido: "GARZON",
    est_segundo_apellido: "ARTUNDUAGA",
    est_primer_nombre: "MARLON",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "NUIP",
    est_doc: 1016032704,
    est_primer_apellido: "LOPEZ",
    est_segundo_apellido: "RAMIREZ",
    est_primer_nombre: "PAULA",
    est_segundo_nombre: "ANDREA",
    est_estado: "RETIRADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083900083,
    est_primer_apellido: "RAMOS",
    est_segundo_apellido: "CARDOZO",
    est_primer_nombre: "NATALY",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1145825351,
    est_primer_apellido: "RODRIGUEZ",
    est_segundo_apellido: "GURRUTE",
    est_primer_nombre: "DEINER",
    est_segundo_nombre: "FERNEY",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "SEGUNDO",
    est_sector: "OFICIAL",
    est_grupo: 201,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083897544,
    est_primer_apellido: "RUIZ",
    est_segundo_apellido: "VARGAS",
    est_primer_nombre: "JULIAN",
    est_segundo_nombre: "DAVID",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144627170,
    est_primer_apellido: "CALDERON",
    est_segundo_apellido: "MUÑOZ",
    est_primer_nombre: "NATALIA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "TERCERO",
    est_sector: "OFICIAL",
    est_grupo: 301,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1144626797,
    est_primer_apellido: "GARZON",
    est_segundo_apellido: "CALDERON",
    est_primer_nombre: "JOSE",
    est_segundo_nombre: "DANIEL",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1079536067,
    est_primer_apellido: "ARTUNDUAGA",
    est_segundo_apellido: "VARGAS",
    est_primer_nombre: "DIANA",
    est_segundo_nombre: "ISABEL",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080933264,
    est_primer_apellido: "CUELLAR",
    est_segundo_apellido: "VARGAS",
    est_primer_nombre: "MAURICIO",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1077230485,
    est_primer_apellido: "GARZON",
    est_segundo_apellido: "ARTUNDUAGA",
    est_primer_nombre: "ALEXIS",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "TI",
    est_doc: 1083886100,
    est_primer_apellido: "MOLINA",
    est_segundo_apellido: "PASAJE",
    est_primer_nombre: "ALMA",
    est_segundo_nombre: "CAMILA",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "CUARTO",
    est_sector: "OFICIAL",
    est_grupo: 401,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1080932523,
    est_primer_apellido: "TRUJILLO",
    est_segundo_apellido: "PERDOMO",
    est_primer_nombre: "DANIELA",
    est_segundo_nombre: "",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083881302,
    est_primer_apellido: "CUELLAR",
    est_segundo_apellido: "CALDERON",
    est_primer_nombre: "NESTOR",
    est_segundo_nombre: "FELIPE",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})
db.estudiantes.insert({
    est_anio: 2018,
    est_secretaria: "TIMANÁ",
    est_dane_ie: 241807000079,
    est_nombre_ie: "IE CASCAJAL",
    est_dane_sede: 24180700007903,
    est_nombre_sede: "EL TOBO",
    est_jornada: "COMPLETA",
    est_calendario: "A",
    est_grado: "QUINTO",
    est_sector: "OFICIAL",
    est_grupo: 501,
    est_modelo_educativo: "ESCUELA NUEVA",
    est_tipo_identificacion: "RC",
    est_doc: 1083881137,
    est_primer_apellido: "GUZMAN",
    est_segundo_apellido: "GIRON",
    est_primer_nombre: "DEINY",
    est_segundo_nombre: "LICETH",
    est_estado: "MATRICULADO",
    est_matricula_contratada: "N",
    est_fuente_recursos: "SGP"
})